services:
  superset:
    build: .
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=otto_superset_secret
    volumes:
      - superset-data:/app/superset_home
    command: bash -c "superset db upgrade && superset fab create-admin --username admin --firstname Admin --lastname Admin --email admin@example.com --password admin || true && superset init && superset run -p 8088 --host 0.0.0.0 --with-threads"
 
volumes:
  superset-data:
 